import type { Photo } from "./types";

/**
 * Licensed photographs for the demonstration listings: stock photography
 * under the Unsplash Licence and Wikimedia Commons images. Attribution for every image is recorded here and
 * shown on the /demonstration page. Generated by scripts/generate-photos.cjs.
 */
export const photosBySlug: Record<string, Photo[]> = {
  "14-louisa-road-birchgrove": [
    { src: "/photos/stock/ext-08.jpg", view: "exterior", alt: "Federation brick house with a gabled roof and deep front verandah", width: 1600, height: 1064, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-02.jpg", view: "living", alt: "Open living room with a linen sofa and the kitchen beyond", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/14-louisa-road-birchgrove/3.jpg", view: "kitchen", alt: "Kitchen opening to a leafy garden", width: 1280, height: 850, credit: "Jeremy Levine, CC BY 2.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Sustainable_Kitchen_-_Flickr_-_Jeremy_Levine_Design.jpg" },
    { src: "/photos/14-louisa-road-birchgrove/5.jpg", view: "outdoor", alt: "Snails Bay foreshore with moored boats", width: 1280, height: 960, credit: "Wikimedia Commons contributor, CC BY 3.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Snails_Bay_Birchgrove_-_panoramio.jpg" },
  ],
  "27-darling-street-balmain": [
    { src: "/photos/27-darling-street-balmain/approach-exterior.jpg", view: "exterior", alt: "Two-storey Victorian house with sandstone walls, a cream iron-lace verandah and a green front door standing open, AI-generated illustration", width: 1920, height: 1080, credit: "AI-generated illustration (Higgsfield Seedance 2.0) for this demonstration. Not a real property." },
    { src: "/photos/27-darling-street-balmain/approach-hall.jpg", view: "living", alt: "Entrance hall with honey timber floorboards running to the rear living room and a sunlit courtyard, AI-generated illustration", width: 1920, height: 1080, credit: "AI-generated illustration (Higgsfield Seedance 2.0) for this demonstration. Not a real property." },
    { src: "/photos/stock/int-01.jpg", view: "living", alt: "Formal sitting room with a curved armchair and framed prints", width: 1600, height: 846, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-05.jpg", view: "kitchen", alt: "Kitchen with dark cabinetry, stone benchtop and timber floors", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/27-darling-street-balmain/4.jpg", view: "bedroom", alt: "Main bedroom in neutral tones", width: 1280, height: 959, credit: "SPL Interiors1, CC BY 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Balanced_Modern_Bedroom_Design_with_Neutral_Tones_and_Layered_Lighting.jpg" },
  ],
  "8-42-wellington-street-rozelle": [
    { src: "/photos/8-42-wellington-street-rozelle/1.jpg", view: "exterior", alt: "Converted brick warehouse with arched windows", width: 1280, height: 720, credit: "Andre Carrotflower, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Vintage_Flats_Apartments_-_fmr_Visco-Meter_Corporation,_Buerk_Tool_et_al._-_Buffalo,_New_York_-_20230204.jpg" },
    { src: "/photos/stock/int-03.jpg", view: "living", alt: "Double-height living space with a curved sofa under soft light", width: 1600, height: 900, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/8-42-wellington-street-rozelle/3.jpg", view: "kitchen", alt: "Bright kitchen with timber benchtop", width: 1280, height: 1920, credit: "Shixart1985, CC BY 2.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Bright_kitchen_on_a_winter_day_with_a_mixer_and_fruits_on_the_counter_near_a_large_window.jpg" },
    { src: "/photos/8-42-wellington-street-rozelle/4.jpg", view: "bedroom", alt: "Mezzanine bedroom under a skylight", width: 1280, height: 854, credit: "Kotivalo, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Bed_under_skylight.jpg" },
  ],
  "5-nelson-street-annandale": [
    { src: "/photos/5-nelson-street-annandale/1.jpg", view: "exterior", alt: "Italianate terrace with rendered façade and parapet", width: 1280, height: 834, credit: "Sardaka, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Italianate_house_Annandale_001a.jpg" },
    { src: "/photos/5-nelson-street-annandale/2.jpg", view: "living", alt: "Living room with grey sofas and warm timber", width: 1280, height: 1066, credit: "This is the CC0 Creative Commons Image taken from the Pixabay., CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Living_Room_Interior_Designer_-_Picker_Online.jpg" },
    { src: "/photos/5-nelson-street-annandale/3.jpg", view: "kitchen", alt: "White kitchen with island and bar stools", width: 1280, height: 1614, credit: "DesignAtFirstSight, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Neugraf-kuchyne-scarlett-rosi.jpg" },
    { src: "/photos/5-nelson-street-annandale/5.jpg", view: "outdoor", alt: "Leafy rear garden with sandstone path", width: 1280, height: 960, credit: "Vic161015, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Wendy%27s_Secret_Garden.jpg" },
  ],
  "112-norton-street-leichhardt": [
    { src: "/photos/112-norton-street-leichhardt/1.jpg", view: "exterior", alt: "Federation semi with tuck-pointed brick and leadlight", width: 1280, height: 960, credit: "Lmc2040, Public domain, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:House_in_Catherine_Street,_Leichhardt,_New_South_Wales,_Australia.jpg" },
    { src: "/photos/112-norton-street-leichhardt/2.jpg", view: "living", alt: "Living room with a neutral sofa and artwork", width: 1280, height: 1600, credit: "Estate Lookup Interiors, CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Spacious_Living_Room_Interior_Design_in_Kolkata_by_Estate_Lookup_Interiors.png" },
    { src: "/photos/112-norton-street-leichhardt/3.jpg", view: "bedroom", alt: "Bedroom with a stylish headboard", width: 1280, height: 854, credit: "Shixart1985, CC BY 2.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Modern_bedroom_design_in_a_stylish_hotel_room_featuring_geometric_patterns_and_soft_linens.jpg" },
  ],
  "3-glover-street-lilyfield": [
    { src: "/photos/stock/hero-01.jpg", view: "exterior", alt: "Two-storey architect-designed house lit at dusk, with full-height glazing to the garden", width: 2000, height: 1555, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-03.jpg", view: "living", alt: "Living room with a curved sofa and a double-height ceiling", width: 1600, height: 900, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-04.jpg", view: "kitchen", alt: "White kitchen with a wide island bench and pendant lights", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/3-glover-street-lilyfield/4.jpg", view: "bedroom", alt: "Main bedroom in neutral tones", width: 1280, height: 959, credit: "SPL Interiors1, CC BY 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Balanced_Modern_Bedroom_Design_with_Neutral_Tones_and_Layered_Lighting.jpg" },
    { src: "/photos/3-glover-street-lilyfield/5.jpg", view: "outdoor", alt: "North-facing pool terrace", width: 1280, height: 960, credit: "Wikimedia Commons contributor, CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Une_piscine_priv%C3%A9e_dans_l%27Ain.JPG" },
  ],
  "19-2-booth-street-annandale": [
    { src: "/photos/stock/ext-07.jpg", view: "exterior", alt: "Contemporary low-rise apartments with balconies behind mature trees", width: 1600, height: 1200, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-01.jpg", view: "living", alt: "Living room with a wall-mounted television and a round armchair", width: 1600, height: 846, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/19-2-booth-street-annandale/2.jpg", view: "kitchen", alt: "Bright living and dining area", width: 1280, height: 854, credit: "Shixart1985, CC BY 2.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Modern_kitchen_and_dining_area_in_a_bright_apartment_on_a_sunny_day_with_simple_decor_and_furniture.jpg" },
  ],
  "41-cameron-street-birchgrove": [
    { src: "/photos/stock/ext-06.jpg", view: "exterior", alt: "Two-storey brick terrace with a first-floor balcony on a quiet street", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-03.jpg", view: "living", alt: "Living room with a curved sofa and a high ceiling", width: 1600, height: 900, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/41-cameron-street-birchgrove/3.jpg", view: "outdoor", alt: "Courtyard garden", width: 1280, height: 960, credit: "Vic161015, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Wendy%27s_Secret_Garden.jpg" },
  ],
  "66-beattie-street-balmain": [
    { src: "/photos/66-beattie-street-balmain/1.jpg", view: "exterior", alt: "Sandstone cottage with a verandah", width: 1280, height: 853, credit: "Sardaka, CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Balmain_cottage_003.jpg" },
    { src: "/photos/66-beattie-street-balmain/2.jpg", view: "outdoor", alt: "Cottage frontage and garden", width: 1280, height: 850, credit: "Sardaka, CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Balmain_cottage_002.jpg" },
    { src: "/photos/66-beattie-street-balmain/3.jpg", view: "outdoor", alt: "Cottage garden", width: 1280, height: 853, credit: "Sardaka, CC0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Balmain_cottage_004.jpg" },
  ],
  "7-foucart-street-rozelle": [
    { src: "/photos/7-foucart-street-rozelle/1.jpg", view: "exterior", alt: "Freestanding federation bungalow", width: 1280, height: 998, credit: "Sardaka, CC BY 3.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:(1)Federation_Bungalow_in_Greenwich.jpg" },
    { src: "/photos/stock/int-01.jpg", view: "living", alt: "Living room with framed prints and a round armchair", width: 1600, height: 846, credit: "Licensed stock photography via Unsplash" },
  ],
  "12-88-victoria-road-rozelle": [
    { src: "/photos/stock/ext-01.jpg", view: "exterior", alt: "Brick apartment building with a jacaranda in flower", width: 1600, height: 1135, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-02.jpg", view: "living", alt: "Open-plan living and kitchen with a linen sofa", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-04.jpg", view: "kitchen", alt: "White kitchen with an island bench and pendant lights", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
  ],
  "30-piper-street-lilyfield": [
    { src: "/photos/stock/ext-03.jpg", view: "exterior", alt: "Weatherboard cottage with a bullnose verandah and a yellow front door", width: 1600, height: 1600, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/stock/int-02.jpg", view: "living", alt: "Living room opening to the kitchen", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
    { src: "/photos/30-piper-street-lilyfield/3.jpg", view: "kitchen", alt: "Cosy kitchen with timber accents", width: 1280, height: 854, credit: "Shixart1985, CC BY 2.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:This_cozy_kitchen_showcases_modern_design_elements.jpg" },
    { src: "/photos/stock/life-03.jpg", view: "outdoor", alt: "Callan Park gardens, a short walk from the house", width: 1600, height: 1067, credit: "Licensed stock photography via Unsplash" },
  ],
  "4-15-johnston-street-annandale": [
    { src: "/photos/4-15-johnston-street-annandale/1.jpg", view: "exterior", alt: "Converted federation mansion on Johnston Street", width: 1280, height: 1808, credit: "Sardaka, CC BY-SA 4.0, via Wikimedia Commons", creditUrl: "https://commons.wikimedia.org/wiki/File:Annandale_house_011.jpg" },
    { src: "/photos/stock/int-03.jpg", view: "living", alt: "Living room with a curved sofa under a high ceiling", width: 1600, height: 900, credit: "Licensed stock photography via Unsplash" },
  ],
};
