// Synthetic fixture for detail-continuity.acceptance.ts. No personal data or live backend.
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import { LeadDrawer } from "../../src/components/operator/lead-drawer";
import { Modal } from "../../src/components/operator/ui";
import type { Lead, LeadDeal, CallScript } from "../../src/lib/leads";
const at = "2026-09-30T00:00:00Z";
// Only the synthetic revision is used by this browser fixture.
const lead: Lead = { id:7, name:"Harbour Sample Dental", vertical:"dental", area:"Sample Bay NSW", address:"12 Example Street", phone:"0491 570 006", emails:["hello@example.invalid"], emailOk:false, website:"https://sample.example.invalid", mapsUrl:"", score:82, pitch:"both", reasons:["Booking requests need a phone call", "The service pages have no clear next step", "The mobile navigation hides the enquiry link"], verified:[true,true,false], status:"call_back", owner:"usman", nextAt:at, lastContactAt:at, createdAt:at };
const deal: LeadDeal = { stage:"contacted",closed:false,evidence:"A sample conversation is recorded",nextAction:"Discuss their booking workflow",owner:"usman",stageSince:at,daysInStage:2,daysInferred:false,stuck:null,contactPref:"Ask for the practice manager. Mornings are best.",issues:[],timeline:[{stage:"contacted",at,evidence:"Sample call",inferred:false}],record:{offer:"both",packageId:"professional",setupCents:null,monthlyCents:null,probability:null,expectedClose:null,contactPref:"Ask for the practice manager. Mornings are best.",updatedBy:"usman",updatedAt:at},stageProbability:0.3,stuckDays:7,monthsCounted:12,economics:{offer:"both",offerLabel:"Website + AI receptionist",packageId:"professional",priceStatus:"approved",setupCents:150000,monthlyCents:109900,valueCents:1468800,valueInclGstCents:1615680,gstBasis:"ex GST",valueSource:"catalogue",websiteCents:150000,receptionistSetup:{cents:149000,status:"proposed"},packageState:{state:"chosen",note:"Professional selected"},probability:0.3,probabilitySource:"stage default",weightedCents:440640,expectedClose:null}};
const script: CallScript = {leadId:7,generatedAt:at,model:"synthetic",pitch:"both",opener:"Hi, is the practice manager available? I’m calling about how you handle new patient enquiries.",discovery:["How do new patients book with you?", "Which calendar does your team use?"],valuePitch:"We can map the call and booking flow with your team, then test it before it goes live.",objections:{price:"Let’s work out whether it would be useful first.",already_have_website:"We can work with the site you already have.",send_email:"What would be helpful to include?",not_now:"When would be a better time?",ask_partner:"We can speak with both of you."},close:"Would a 15-minute demo be useful?",followupEmail:{subject:"Your booking workflow",body:"Here is the summary we discussed."},compliance:{callWindow:{open:true,why:"Synthetic daytime"},dncReminder:"Check the DNC Register",noInventedClaims:"Verified facts only"}};
const qc = new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}});
lead.editVersion = "synthetic-lead-v1";
qc.setQueryData(["leads-detail",7],{lead,deal,pipeline:{stage:"contacted",evidence:deal.evidence,nextAction:deal.nextAction,owner:"usman",closed:false},drafts:["sample-proposal.md"],activities:[{id:1,leadId:7,at,kind:"call",outcome:"call_back",note:"The practice manager asked for a short demo.",by:"usman"}],issues:{checkedAt:at,status:"checked",statusNote:"Synthetic review",hook:"Ask how patients book",top:[{code:"booking",finding:"The booking page asks patients to call",severity:2,offer:"both",url:lead.website,seen:"Call the practice to book",source:"site"}]}});
qc.setQueryData(["lead-script",7],{script});
qc.setQueryData(["lead-thumb",7],{thumbs:{}});
qc.setQueryData(["lead-seo-audit",7],{audit:null});
qc.setQueryData(["leads-summary"],{callWindow:{open:true,why:"Synthetic daytime"}});
Object.assign(window,{getSyntheticDetail:()=>qc.getQueryData(["leads-detail",7]),setSyntheticLead:(patch:Partial<Lead>)=>qc.setQueryData(["leads-detail",7],(data:any)=>({...data,lead:{...lead,...patch}}))});
function Review() { const [open,setOpen]=useState(false); return <div className="operator-shell min-h-screen bg-background p-8 text-foreground"><h1 className="text-xl">Synthetic detail review</h1><button id="open-lead" className="mt-6" onClick={()=>setOpen(true)}>Open sample lead</button>{location.pathname==="/memory-detail" ? <Modal open={open} onClose={()=>setOpen(false)} title="Sample business note" description="Synthetic memory fixture"><div className="op-detail-meta">Saved today · Sample source</div><div className="op-detail-text">The team uses a shared calendar. This is fabricated review content.</div><button className="op-button">Edit note</button></Modal> : <LeadDrawer id={open ? 7 : null} onClose={()=>setOpen(false)} by="usman" onChanged={()=>{}}/>}</div>}
createRoot(document.getElementById("root")!).render(<QueryClientProvider client={qc}><Review/></QueryClientProvider>);
