<#
.SYNOPSIS
  CUTOVER ONLY. Registers the Hermes gateway on Ryzen-PC as a boot-time Scheduled Task (S4U logon,
  so it starts without anyone logged in). Staging deliberately does NOT run this.

.DESCRIPTION
  Hermes' own `hermes gateway install` registers a LogonTrigger + InteractiveToken task, which only
  fires after a user logs in. Ryzen has no auto-login, so this script registers a BootTrigger +
  S4U task instead (same model as the \MU\ hub tasks).

  Dry run by default: prints what it would do. Pass -Register to act, and -MainGatewayStopped to
  confirm the main PC's gateway is stopped (two gateways must never poll the same Telegram bot).

  Run on Ryzen, elevated:
    powershell -NoProfile -ExecutionPolicy Bypass -File Register-HermesGateway-Ryzen.ps1 -Register -MainGatewayStopped -StartNow
  Undo:
    powershell -NoProfile -ExecutionPolicy Bypass -File Register-HermesGateway-Ryzen.ps1 -Unregister
#>
[CmdletBinding()]
param(
  [switch]$Register,
  [switch]$Unregister,
  [switch]$MainGatewayStopped,
  [switch]$StartNow,
  [string]$TaskPath = '\MU\',
  [string]$TaskName = 'MU Hermes Gateway',
  [string]$User = 'RYZEN-PC\mkhan',
  [string]$HermesHome = 'C:\Users\mkhan\AppData\Local\hermes',
  [string]$HubBin = 'C:\mu-hub\bin'          # bun.exe lives here; the lead/hub scripts look it up via PATH
)
$ErrorActionPreference = 'Stop'
$full = $TaskPath + $TaskName
$gwDir = Join-Path $HermesHome 'gateway-service'
$vbs = Join-Path $gwDir 'Hermes_Gateway.vbs'
$venv = Join-Path $HermesHome 'hermes-agent\venv'
$py = Join-Path $venv 'Scripts\python.exe'

if ($Unregister) {
  Get-Process -Name python, pythonw -ErrorAction SilentlyContinue | Out-Null
  if (Get-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -Confirm:$false
    "Unregistered $full"
  } else { "$full is not registered" }
  "Stop a running gateway with: $HermesHome\bin\hermes.exe gateway stop"
  return
}

# Launcher: same content Hermes generates (env + `gateway run`), Ryzen paths, plus the hub's bun on PATH.
$launcher = @"
' Hermes Agent Gateway - Ryzen-PC boot launcher (generated by Register-HermesGateway-Ryzen.ps1)
Option Explicit
Dim sh, env, existing_pp
Set sh = CreateObject("WScript.Shell")
Set env = sh.Environment("PROCESS")
env.Item("HERMES_HOME") = "$HermesHome"
env.Item("PYTHONIOENCODING") = "utf-8"
env.Item("HERMES_GATEWAY_DETACHED") = "1"
env.Item("HERMES_SUPERVISED_CHILD") = "1"
env.Item("VIRTUAL_ENV") = "$venv"
env.Item("PATH") = "$HubBin;" & env.Item("PATH")
existing_pp = env.Item("PYTHONPATH")
If Len(existing_pp) > 0 Then
  env.Item("PYTHONPATH") = "$HermesHome\hermes-agent;" & existing_pp
Else
  env.Item("PYTHONPATH") = "$HermesHome\hermes-agent"
End If
sh.CurrentDirectory = "$HermesHome"
sh.Run """$py"" -m hermes_cli.main gateway run", 0, False
"@

$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo><Description>Hermes gateway (Telegram/WhatsApp + cron) for M&amp;U on Ryzen-PC. Boot-time, S4U.</Description></RegistrationInfo>
  <Triggers><BootTrigger><Enabled>true</Enabled><Delay>PT90S</Delay></BootTrigger></Triggers>
  <Principals><Principal id="Author"><UserId>$User</UserId><LogonType>S4U</LogonType><RunLevel>LeastPrivilege</RunLevel></Principal></Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings><StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure><Interval>PT1M</Interval><Count>999</Count></RestartOnFailure>
  </Settings>
  <Actions Context="Author"><Exec><Command>wscript.exe</Command><Arguments>//B //Nologo "$vbs"</Arguments></Exec></Actions>
</Task>
"@

"Task      : $full  (BootTrigger +90s, S4U as $User, restart on failure)"
"Launcher  : $vbs"
"Action    : wscript.exe //B //Nologo `"$vbs`"  ->  $py -m hermes_cli.main gateway run"
if (-not $Register) { "DRY RUN - nothing written. Re-run with -Register -MainGatewayStopped to register."; return }

if (-not $MainGatewayStopped) { throw 'Refusing: pass -MainGatewayStopped once the main PC gateway is stopped and its autostart removed.' }
foreach ($p in @($py, (Join-Path $HermesHome '.env'), (Join-Path $HermesHome 'config.yaml'))) { if (-not (Test-Path $p)) { throw "Missing $p" } }
if (-not (Test-Path (Join-Path $HermesHome 'auth.json'))) { Write-Warning 'No auth.json: sign in first (hermes auth add openai-codex --type oauth ...). The gateway will start but model calls will fail.' }
$running = Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -match 'hermes_cli[.\\/]main(\.py)?"?\s+gateway\s+run' }
if ($running) { throw "A Hermes gateway is already running on this PC (PID $($running.ProcessId -join ','))." }

New-Item -ItemType Directory -Force $gwDir | Out-Null
[IO.File]::WriteAllText($vbs, ($launcher -replace "`r?`n", "`r`n"), [Text.Encoding]::ASCII)
$xmlPath = Join-Path $env:TEMP 'mu-hermes-gateway.task.xml'
[IO.File]::WriteAllText($xmlPath, $xml, [Text.Encoding]::Unicode)
try { schtasks /Create /F /TN $full /XML $xmlPath | Out-Host } finally { Remove-Item $xmlPath -Force -ErrorAction SilentlyContinue }
if ($LASTEXITCODE -ne 0) { throw "schtasks /Create failed ($LASTEXITCODE)" }
"Registered $full"
if ($StartNow) { Start-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName; 'Started. Check: hermes gateway status' }
