/** Every file route in src/routes at 491b8ee0 (44 files), with a concrete URL for the parameterised ones, plus a 404. Shared by the sweep and the inventory. */
export const ROUTES: { path: string; file: string; expectRedirect?: RegExp }[] = [
  { path: "/", file: "index.tsx", expectRedirect: /\/business$/ },
  { path: "/today", file: "today.tsx", expectRedirect: /\/business/ },
  { path: "/workspace", file: "workspace.tsx", expectRedirect: /\/business/ },
  { path: "/business", file: "business.tsx" },
  { path: "/jarvis", file: "jarvis.tsx" },
  { path: "/chat", file: "chat.tsx" },
  { path: "/agents/workspace", file: "agents.workspace.tsx" },
  { path: "/agents/workspace/builder", file: "agents.workspace.$botId.tsx" },
  { path: "/agents/workspace/no-such-bot", file: "agents.workspace.$botId.tsx (unknown id)" },
  { path: "/agents/hermes", file: "agents.hermes.tsx" },
  { path: "/agents/claude-code", file: "agents.claude-code.tsx" },
  { path: "/agents/openclaw", file: "agents.openclaw.tsx" },
  { path: "/automations", file: "automations.tsx" },
  { path: "/activity", file: "activity.tsx" },
  { path: "/receptionist", file: "receptionist.tsx" },
  { path: "/work", file: "work.tsx" },
  { path: "/leads", file: "leads.tsx" },
  { path: "/websites", file: "websites.tsx" },
  { path: "/crm", file: "crm.tsx (candidate)" },
  { path: "/crm?view=pipeline", file: "crm.tsx pipeline view (candidate)" },
  { path: "/workspaces", file: "workspaces.index.tsx" },
  { path: "/workspaces/no-such-workspace", file: "workspaces.$id.tsx (unknown id)" },
  { path: "/coding", file: "coding.index.tsx" },
  { path: "/coding/no-such-job", file: "coding.$jobId.tsx (unknown id)" },
  { path: "/computers", file: "computers.tsx" },
  { path: "/memory", file: "memory.tsx" },
  { path: "/memory/vault", file: "memory_.vault.tsx" },
  { path: "/memory-map", file: "memory-map.tsx" },
  { path: "/codegraph", file: "codegraph.tsx" },
  { path: "/finance", file: "finance.tsx" },
  { path: "/usage", file: "usage.tsx" },
  { path: "/studio", file: "studio.tsx" },
  { path: "/design", file: "design.tsx" },
  { path: "/motion", file: "motion.tsx" },
  { path: "/transitions", file: "transitions.tsx" },
  { path: "/share", file: "share.tsx" },
  { path: "/system", file: "system.tsx" },
  { path: "/models", file: "models.tsx" },
  { path: "/skills", file: "skills.tsx" },
  { path: "/skill-drafts", file: "skill-drafts.tsx" },
  { path: "/settings", file: "settings.tsx" },
  { path: "/setup", file: "setup.tsx" },
  { path: "/inbox", file: "inbox.tsx" },
  { path: "/inbox-triage", file: "inbox-triage.tsx" },
  { path: "/calendar", file: "calendar.tsx" },
  { path: "/operations", file: "operations.tsx" },
  { path: "/hud", file: "hud.tsx" },
  { path: "/dashboard", file: "dashboard.tsx" },
  { path: "/no-such-page", file: "(404)" },
];
