import { describe, expect, test } from "bun:test";
import { bookmarksIntent, matchApp, parsePcRequest, pcIntent, type StartApp } from "./pc-hands";
import { browserIntent } from "./browser-hands";

const apps: StartApp[] = [
  { name: "Notepad", id: "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App" },
  { name: "Google Chrome", id: "Chrome" },
  { name: "Jarvis Chrome", id: "Microsoft.AutoGenerated.{X}" },
  { name: "Visual Studio Code", id: "Microsoft.VisualStudioCode" },
  { name: "Free Claude Code", id: "C:\\Users\\x\\fcc-desktop.exe" },
  { name: "Spotify", id: "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify" },
  { name: "WhatsApp", id: "5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App" },
  { name: "Settings", id: "windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel" },
  { name: "File Explorer", id: "Microsoft.Windows.Explorer" },
];

describe("which app he means", () => {
  test("names and aliases", () => {
    expect(matchApp(apps, "notepad")?.name).toBe("Notepad");
    expect(matchApp(apps, "chrome")?.name).toBe("Google Chrome");
    expect(matchApp(apps, "vs code")?.name).toBe("Visual Studio Code");
    expect(matchApp(apps, "code")?.name).toBe("Visual Studio Code");
    expect(matchApp(apps, "explorer")?.name).toBe("File Explorer");
    expect(matchApp(apps, "photoshop")).toBeNull();
  });
});

describe("plain PC commands skip Jev", () => {
  test("opens, media, volume, lock", () => {
    expect(pcIntent("open notepad", apps)).toEqual({ action: "open_app", target: "Notepad" });
    expect(pcIntent("Jarvis, can you launch Spotify please", apps)).toEqual({ action: "open_app", target: "Spotify" });
    expect(pcIntent("open WhatsApp", apps)).toEqual({ action: "open_app", target: "WhatsApp" });
    expect(pcIntent("open my downloads", apps)).toEqual({ action: "open_folder", target: "Downloads" });
    expect(pcIntent("next song", apps)).toEqual({ action: "media", target: "next" });
    expect(pcIntent("pause the music", apps)).toEqual({ action: "media", target: "play_pause" });
    expect(pcIntent("volume up", apps)).toEqual({ action: "volume", target: "up" });
    expect(pcIntent("mute", apps)).toEqual({ action: "volume", target: "mute" });
    expect(pcIntent("lock my pc", apps)).toEqual({ action: "lock" });
    expect(pcIntent("boot up vs code", apps)).toEqual({ action: "open_app", target: "Visual Studio Code" });
    expect(pcIntent("fire up notepad", apps)).toEqual({ action: "open_app", target: "Notepad" });
  });
  test("OS pages, websites and real tasks are left to Jev and the brain", () => {
    expect(pcIntent("open my inbox", apps)).toBeNull();
    // (J4: bare "settings" is the OS page, as the OS's own name for it; the Windows Settings app is "Windows settings".)
    expect(pcIntent("open settings", apps)).toBeNull();
    expect(pcIntent("open windows settings", apps)).toEqual({ action: "open_app", target: "Settings" });
    expect(pcIntent("open the settings app", apps)).toEqual({ action: "open_app", target: "Settings" });
    for (const page of ["open home", "open studio", "open today", "open work", "open finance", "open vault"]) expect(pcIntent(page, apps)).toBeNull();
    // "OS settings" is the Agentic OS page, left to the router's navigate.
    expect(pcIntent("open the os settings", apps)).toBeNull();
    expect(pcIntent("open jarvis settings", apps)).toBeNull();
    expect(pcIntent("open YouTube", apps)).toBeNull();
    expect(pcIntent("open the dental project in VS Code", apps)).toBeNull();
    expect(pcIntent("open WhatsApp and message Mehroz", apps)).toBeNull();
    expect(pcIntent("open photoshop", apps)).toBeNull();
    expect(pcIntent("what's the weather", apps)).toBeNull();
  });
  test("music goes to media keys, videos to the browser", () => {
    expect(browserIntent("pause the music")).toBeNull();
    expect(browserIntent("pause the video")).toEqual({ action: "pause" });
  });
  test("request validation", () => {
    expect(parsePcRequest({ action: "volume", target: "up" })).toEqual({ action: "volume", target: "up" });
    expect(() => parsePcRequest({ action: "volume", target: "max" })).toThrow();
    expect(() => parsePcRequest({ action: "format", target: "c" })).toThrow();
  });
});

describe("bookmarks: a direct rule route, never the screen clicking loop", () => {
  test("recognises the phrasing (and its variants)", () => {
    expect(bookmarksIntent("show my bookmarks in Chrome")).toBe(true);
    expect(bookmarksIntent("open my bookmarks")).toBe(true);
    expect(bookmarksIntent("bookmarks manager")).toBe(true);
    expect(bookmarksIntent("open bookmarks")).toBe(true);
    expect(bookmarksIntent("show bookmarks")).toBe(true);
    expect(bookmarksIntent("pull up my chrome bookmarks")).toBe(true);
    expect(bookmarksIntent("Jarvis, open my bookmarks please")).toBe(true);
    expect(bookmarksIntent("chrome bookmarks manager")).toBe(true);
  });
  test("leaves unrelated requests alone", () => {
    expect(bookmarksIntent("open chrome")).toBe(false);
    expect(bookmarksIntent("bookmark this page")).toBe(false);
    expect(bookmarksIntent("click the bookmarks star")).toBe(false);
    expect(bookmarksIntent("what's on my screen")).toBe(false);
    expect(bookmarksIntent("")).toBe(false);
  });
  test("pcIntent routes it to open_bookmarks before the generic 'open …' app match", () => {
    expect(pcIntent("show my bookmarks in Chrome", apps)).toEqual({ action: "open_bookmarks" });
    expect(pcIntent("open my bookmarks", apps)).toEqual({ action: "open_bookmarks" });
    expect(pcIntent("bookmarks manager", apps)).toEqual({ action: "open_bookmarks" });
    // Still just "open Chrome" (the app), not bookmarks.
    expect(pcIntent("open chrome", apps)).toEqual({ action: "open_app", target: "Google Chrome" });
  });
  test("request validation accepts it with no target", () => {
    expect(parsePcRequest({ action: "open_bookmarks" })).toEqual({ action: "open_bookmarks" });
  });
});

describe("speech-to-text slips still find the app (fuzzy fallback)", () => {
  test("misspellings and half-heard aliases", () => {
    expect(matchApp(apps, "spotfy")?.name).toBe("Spotify");
    expect(matchApp(apps, "whatsap")?.name).toBe("WhatsApp");
    expect(matchApp(apps, "vs cod")?.name).toBe("Visual Studio Code");
    expect(matchApp(apps, "notpad")?.name).toBe("Notepad");
    expect(matchApp(apps, "chrom")?.name).toBe("Google Chrome");
    expect(pcIntent("open spotfy", apps)).toEqual({ action: "open_app", target: "Spotify" });
    expect(pcIntent("open whatsap", apps)).toEqual({ action: "open_app", target: "WhatsApp" });
    expect(pcIntent("open vs cod", apps)).toEqual({ action: "open_app", target: "Visual Studio Code" });
  });
  test("too far off, or too short, is still no match", () => {
    expect(matchApp(apps, "photoshop")).toBeNull();
    expect(matchApp(apps, "spoon")).toBeNull();
    expect(matchApp(apps, "spt")).toBeNull();
    expect(matchApp(apps, "spotfy", false)).toBeNull();
  });
  test("fuzzy never steals OS pages or websites", () => {
    const withYouTube = [...apps, { name: "YouTube Music", id: "YTM" }, { name: "Calendar", id: "Cal" }];
    expect(pcIntent("open youtub", withYouTube)).toBeNull();
    expect(pcIntent("open calender", withYouTube)).toBeNull();
    expect(pcIntent("open inbx", withYouTube)).toBeNull();
    expect(pcIntent("open linkedn", withYouTube)).toBeNull();
    expect(pcIntent("open the dashbord", withYouTube)).toBeNull();
  });
});
