/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TransitionsRouteImport } from './routes/transitions'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SkillDraftsRouteImport } from './routes/skill-drafts'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryMapRouteImport } from './routes/memory-map'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as InboxTriageRouteImport } from './routes/inbox-triage'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HudRouteImport } from './routes/hud'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComputersRouteImport } from './routes/computers'
import { Route as CodegraphRouteImport } from './routes/codegraph'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as CodingIndexRouteImport } from './routes/coding.index'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces.$id'
import { Route as MemoryVaultRouteImport } from './routes/memory_.vault'
import { Route as CodingJobIdRouteImport } from './routes/coding.$jobId'
import { Route as AgentsOpenclawRouteImport } from './routes/agents.openclaw'
import { Route as AgentsHermesRouteImport } from './routes/agents.hermes'
import { Route as AgentsClaudeCodeRouteImport } from './routes/agents.claude-code'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionsRoute = TransitionsRouteImport.update({
  id: '/transitions',
  path: '/transitions',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDraftsRoute = SkillDraftsRouteImport.update({
  id: '/skill-drafts',
  path: '/skill-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryMapRoute = MemoryMapRouteImport.update({
  id: '/memory-map',
  path: '/memory-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxTriageRoute = InboxTriageRouteImport.update({
  id: '/inbox-triage',
  path: '/inbox-triage',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputersRoute = ComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => rootRouteImport,
} as any)
const CodegraphRoute = CodegraphRouteImport.update({
  id: '/codegraph',
  path: '/codegraph',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingIndexRoute = CodingIndexRouteImport.update({
  id: '/coding/',
  path: '/coding/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryVaultRoute = MemoryVaultRouteImport.update({
  id: '/memory_/vault',
  path: '/memory/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingJobIdRoute = CodingJobIdRouteImport.update({
  id: '/coding/$jobId',
  path: '/coding/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOpenclawRoute = AgentsOpenclawRouteImport.update({
  id: '/agents/openclaw',
  path: '/agents/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHermesRoute = AgentsHermesRouteImport.update({
  id: '/agents/hermes',
  path: '/agents/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClaudeCodeRoute = AgentsClaudeCodeRouteImport.update({
  id: '/agents/claude-code',
  path: '/agents/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/automations': typeof AutomationsRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/codegraph': typeof CodegraphRoute
  '/computers': typeof ComputersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/finance': typeof FinanceRoute
  '/hud': typeof HudRoute
  '/inbox': typeof InboxRoute
  '/inbox-triage': typeof InboxTriageRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/memory': typeof MemoryRoute
  '/memory-map': typeof MemoryMapRoute
  '/models': typeof ModelsRoute
  '/motion': typeof MotionRoute
  '/operations': typeof OperationsRoute
  '/receptionist': typeof ReceptionistRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skill-drafts': typeof SkillDraftsRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/system': typeof SystemRoute
  '/today': typeof TodayRoute
  '/transitions': typeof TransitionsRoute
  '/usage': typeof UsageRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/coding/$jobId': typeof CodingJobIdRoute
  '/memory/vault': typeof MemoryVaultRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/coding/': typeof CodingIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/automations': typeof AutomationsRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/codegraph': typeof CodegraphRoute
  '/computers': typeof ComputersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/finance': typeof FinanceRoute
  '/hud': typeof HudRoute
  '/inbox': typeof InboxRoute
  '/inbox-triage': typeof InboxTriageRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/memory': typeof MemoryRoute
  '/memory-map': typeof MemoryMapRoute
  '/models': typeof ModelsRoute
  '/motion': typeof MotionRoute
  '/operations': typeof OperationsRoute
  '/receptionist': typeof ReceptionistRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skill-drafts': typeof SkillDraftsRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/system': typeof SystemRoute
  '/today': typeof TodayRoute
  '/transitions': typeof TransitionsRoute
  '/usage': typeof UsageRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/coding/$jobId': typeof CodingJobIdRoute
  '/memory/vault': typeof MemoryVaultRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/coding': typeof CodingIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/automations': typeof AutomationsRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/codegraph': typeof CodegraphRoute
  '/computers': typeof ComputersRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/finance': typeof FinanceRoute
  '/hud': typeof HudRoute
  '/inbox': typeof InboxRoute
  '/inbox-triage': typeof InboxTriageRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/memory': typeof MemoryRoute
  '/memory-map': typeof MemoryMapRoute
  '/models': typeof ModelsRoute
  '/motion': typeof MotionRoute
  '/operations': typeof OperationsRoute
  '/receptionist': typeof ReceptionistRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skill-drafts': typeof SkillDraftsRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/system': typeof SystemRoute
  '/today': typeof TodayRoute
  '/transitions': typeof TransitionsRoute
  '/usage': typeof UsageRoute
  '/websites': typeof WebsitesRoute
  '/work': typeof WorkRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/coding/$jobId': typeof CodingJobIdRoute
  '/memory_/vault': typeof MemoryVaultRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/coding/': typeof CodingIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/automations'
    | '/business'
    | '/calendar'
    | '/chat'
    | '/codegraph'
    | '/computers'
    | '/dashboard'
    | '/design'
    | '/finance'
    | '/hud'
    | '/inbox'
    | '/inbox-triage'
    | '/jarvis'
    | '/leads'
    | '/memory'
    | '/memory-map'
    | '/models'
    | '/motion'
    | '/operations'
    | '/receptionist'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skill-drafts'
    | '/skills'
    | '/studio'
    | '/system'
    | '/today'
    | '/transitions'
    | '/usage'
    | '/websites'
    | '/work'
    | '/workspace'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/coding/$jobId'
    | '/memory/vault'
    | '/workspaces/$id'
    | '/coding/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/automations'
    | '/business'
    | '/calendar'
    | '/chat'
    | '/codegraph'
    | '/computers'
    | '/dashboard'
    | '/design'
    | '/finance'
    | '/hud'
    | '/inbox'
    | '/inbox-triage'
    | '/jarvis'
    | '/leads'
    | '/memory'
    | '/memory-map'
    | '/models'
    | '/motion'
    | '/operations'
    | '/receptionist'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skill-drafts'
    | '/skills'
    | '/studio'
    | '/system'
    | '/today'
    | '/transitions'
    | '/usage'
    | '/websites'
    | '/work'
    | '/workspace'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/coding/$jobId'
    | '/memory/vault'
    | '/workspaces/$id'
    | '/coding'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/automations'
    | '/business'
    | '/calendar'
    | '/chat'
    | '/codegraph'
    | '/computers'
    | '/dashboard'
    | '/design'
    | '/finance'
    | '/hud'
    | '/inbox'
    | '/inbox-triage'
    | '/jarvis'
    | '/leads'
    | '/memory'
    | '/memory-map'
    | '/models'
    | '/motion'
    | '/operations'
    | '/receptionist'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skill-drafts'
    | '/skills'
    | '/studio'
    | '/system'
    | '/today'
    | '/transitions'
    | '/usage'
    | '/websites'
    | '/work'
    | '/workspace'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/coding/$jobId'
    | '/memory_/vault'
    | '/workspaces/$id'
    | '/coding/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AutomationsRoute: typeof AutomationsRoute
  BusinessRoute: typeof BusinessRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  CodegraphRoute: typeof CodegraphRoute
  ComputersRoute: typeof ComputersRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  FinanceRoute: typeof FinanceRoute
  HudRoute: typeof HudRoute
  InboxRoute: typeof InboxRoute
  InboxTriageRoute: typeof InboxTriageRoute
  JarvisRoute: typeof JarvisRoute
  LeadsRoute: typeof LeadsRoute
  MemoryRoute: typeof MemoryRoute
  MemoryMapRoute: typeof MemoryMapRoute
  ModelsRoute: typeof ModelsRoute
  MotionRoute: typeof MotionRoute
  OperationsRoute: typeof OperationsRoute
  ReceptionistRoute: typeof ReceptionistRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShareRoute: typeof ShareRoute
  SkillDraftsRoute: typeof SkillDraftsRoute
  SkillsRoute: typeof SkillsRoute
  StudioRoute: typeof StudioRoute
  SystemRoute: typeof SystemRoute
  TodayRoute: typeof TodayRoute
  TransitionsRoute: typeof TransitionsRoute
  UsageRoute: typeof UsageRoute
  WebsitesRoute: typeof WebsitesRoute
  WorkRoute: typeof WorkRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AgentsClaudeCodeRoute: typeof AgentsClaudeCodeRoute
  AgentsHermesRoute: typeof AgentsHermesRoute
  AgentsOpenclawRoute: typeof AgentsOpenclawRoute
  CodingJobIdRoute: typeof CodingJobIdRoute
  MemoryVaultRoute: typeof MemoryVaultRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
  CodingIndexRoute: typeof CodingIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transitions': {
      id: '/transitions'
      path: '/transitions'
      fullPath: '/transitions'
      preLoaderRoute: typeof TransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-drafts': {
      id: '/skill-drafts'
      path: '/skill-drafts'
      fullPath: '/skill-drafts'
      preLoaderRoute: typeof SkillDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-map': {
      id: '/memory-map'
      path: '/memory-map'
      fullPath: '/memory-map'
      preLoaderRoute: typeof MemoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-triage': {
      id: '/inbox-triage'
      path: '/inbox-triage'
      fullPath: '/inbox-triage'
      preLoaderRoute: typeof InboxTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computers': {
      id: '/computers'
      path: '/computers'
      fullPath: '/computers'
      preLoaderRoute: typeof ComputersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codegraph': {
      id: '/codegraph'
      path: '/codegraph'
      fullPath: '/codegraph'
      preLoaderRoute: typeof CodegraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding/': {
      id: '/coding/'
      path: '/coding'
      fullPath: '/coding/'
      preLoaderRoute: typeof CodingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$id': {
      id: '/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory_/vault': {
      id: '/memory_/vault'
      path: '/memory/vault'
      fullPath: '/memory/vault'
      preLoaderRoute: typeof MemoryVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding/$jobId': {
      id: '/coding/$jobId'
      path: '/coding/$jobId'
      fullPath: '/coding/$jobId'
      preLoaderRoute: typeof CodingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/openclaw': {
      id: '/agents/openclaw'
      path: '/agents/openclaw'
      fullPath: '/agents/openclaw'
      preLoaderRoute: typeof AgentsOpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/hermes': {
      id: '/agents/hermes'
      path: '/agents/hermes'
      fullPath: '/agents/hermes'
      preLoaderRoute: typeof AgentsHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/claude-code': {
      id: '/agents/claude-code'
      path: '/agents/claude-code'
      fullPath: '/agents/claude-code'
      preLoaderRoute: typeof AgentsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AutomationsRoute: AutomationsRoute,
  BusinessRoute: BusinessRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  CodegraphRoute: CodegraphRoute,
  ComputersRoute: ComputersRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  FinanceRoute: FinanceRoute,
  HudRoute: HudRoute,
  InboxRoute: InboxRoute,
  InboxTriageRoute: InboxTriageRoute,
  JarvisRoute: JarvisRoute,
  LeadsRoute: LeadsRoute,
  MemoryRoute: MemoryRoute,
  MemoryMapRoute: MemoryMapRoute,
  ModelsRoute: ModelsRoute,
  MotionRoute: MotionRoute,
  OperationsRoute: OperationsRoute,
  ReceptionistRoute: ReceptionistRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShareRoute: ShareRoute,
  SkillDraftsRoute: SkillDraftsRoute,
  SkillsRoute: SkillsRoute,
  StudioRoute: StudioRoute,
  SystemRoute: SystemRoute,
  TodayRoute: TodayRoute,
  TransitionsRoute: TransitionsRoute,
  UsageRoute: UsageRoute,
  WebsitesRoute: WebsitesRoute,
  WorkRoute: WorkRoute,
  WorkspaceRoute: WorkspaceRoute,
  AgentsClaudeCodeRoute: AgentsClaudeCodeRoute,
  AgentsHermesRoute: AgentsHermesRoute,
  AgentsOpenclawRoute: AgentsOpenclawRoute,
  CodingJobIdRoute: CodingJobIdRoute,
  MemoryVaultRoute: MemoryVaultRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
  CodingIndexRoute: CodingIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
