import type { Company, CrmSnapshot, Deal, Task } from "../../../scripts/crm/types";
import { SALES_STAGES } from "../../../scripts/crm/types";
export const company = (id: string, extra: Partial<Company> = {}): Company => ({
  id,
  version: 1,
  createdAt: "2026-10-01T00:00:00Z",
  updatedAt: "2026-10-01T00:00:00Z",
  name: `Company ${id}`,
  industry: "Dental",
  website: "",
  locality: "Sydney",
  address: "",
  timezone: "Australia/Sydney",
  phone: "0412 345 678",
  emails: [],
  owner: "usman",
  tags: [],
  source: { kind: "manual", reference: "", attribution: "" },
  fieldSources: {},
  status: "prospect",
  notes: "",
  doNotContact: false,
  emailAllowed: false,
  excluded: false,
  excludedReason: "",
  mergedInto: null,
  legacyLeadId: null,
  websiteCheck: "not-checked",
  websiteCheckedAt: null,
  ...extra,
});
export const snapshot = (): CrmSnapshot => ({
  schemaVersion: 1,
  generatedAt: "2026-10-02T00:00:00Z",
  companies: [
    company("a"),
    company("b", { doNotContact: true, owner: "mehroz", name: "Müller Clinic" }),
  ],
  contacts: [],
  deals: [],
  projects: [],
  tasks: [],
  activities: [],
  documents: [],
  pipelines: [
    {
      id: "sales",
      name: "Sales",
      version: 1,
      createdAt: "",
      updatedAt: "",
      stages: [...SALES_STAGES],
    },
  ],
});
export const task = (dueAt: string | null): Task => ({
  id: "t",
  companyId: "a",
  title: "Call",
  description: "",
  kind: "follow-up",
  status: "open",
  owner: "usman",
  dueAt,
  completedAt: null,
  dealId: null,
  projectId: null,
  contactId: null,
  legacyLeadId: null,
  version: 1,
  createdAt: "",
  updatedAt: "",
});
export const deal = (stageId: string, oneOffCents: number, recurringCents = 0): Deal => ({
  id: stageId,
  companyId: "a",
  title: stageId,
  owner: "usman",
  contactIds: [],
  service: "Website",
  scope: "",
  pipelineId: "sales",
  stageId,
  oneOffCents,
  recurringCents,
  currency: "AUD",
  gstTreatment: "exclusive",
  probability: null,
  expectedClose: null,
  nextAction: "",
  nextActionDue: null,
  closeReason: "",
  stageHistory: [],
  legacyLeadId: null,
  catalogueId: null,
  commercialBasis: "agreed",
  version: 1,
  createdAt: "",
  updatedAt: "",
});
