import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import type { IncomingMessage, ServerResponse } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DeviceStore } from "../devices/store";
import { syntheticTailnetForTests } from "../remote-access";
import { createPrincipalGate } from "./gate";
import { createLocalOwnerProof, readLocalOwnerToken } from "./local-owner-token";
import { ROUTES } from "./routes";

/**
 * Test support: the identity gate's decision for every ROUTES entry, for each method class and each kind
 * of caller, GENERATED by running the real gate (not hand-written per route). The hub-role tests compare
 * the table the gate produces for `pc` and `cloud` with the one the pre-`server` code produced
 * (fixtures/legacy-route-decisions.json), and diff `server` against `pc`.
 *
 * Synthetic people, logins and tokens only. No real people.json, sessions or credentials are read.
 */

export const MATRIX_TAILNET = "matrix-hub.tail-test.ts.net";
export const MATRIX_INTERNAL = "matrix-internal-page-token";
const LOGIN = { usman: "owner@example.test", mehroz: "partner@example.test" };

export const CALLER_KINDS = [
  "loopback-owner", // the owner's browser or a local program at the hub
  "tailnet-founder", // Serve-verified login, no session cookie (a bare login: a process)
  "paired-founder", // Serve-verified login holding a live, confirmed session cookie (a human)
  "companion-remote", // a founder's companion bearer token, arriving through Serve
  "companion-local", // a companion bearer token presented on the hub's own loopback
  "bridge-client", // a computers-bridge client: x-mu-bridge: 1 with a shared computer's token
  "anonymous-lan", // a non-loopback socket, nothing else
  "forged-lan", // a non-loopback socket forging Serve's headers
  "forged-loopback", // a plain loopback request forging Tailscale-User-Login and a .ts.net Host
] as const;
export type CallerKind = (typeof CALLER_KINDS)[number];

export type MatrixRole = "pc" | "cloud" | "server" | undefined;

/** How a loopback request presents the local-owner proof (server role). The default for "loopback-owner" in server role is "header". */
export type ProofMode = "none" | "wrong" | "header" | "bearer";

export type Rig = {
  /** The local-owner token (server role only; a test may rotate the file). Never printed. */
  token(): string | null;
  tokenFile: string;
  /** The paired founder's (Mehroz's) live session cookie value, for tests that build their own Cookie header. */
  pairedCookie: string;
  /** The gate's answer for one request: HTTP status, or 200 when it let the request through. */
  decide(kind: CallerKind, method: string, path: string, extra?: Record<string, string>, onReach?: (req: IncomingMessage) => void, opts?: { proof?: ProofMode }): { status: number; reached: boolean; body: any; headers: Record<string, string | undefined> };
  close(): void;
};

export function makeRig(role: MatrixRole): Rig {
  const root = mkdtempSync(join(tmpdir(), "role-matrix-"));
  mkdirSync(join(root, ".operator-data"));
  writeFileSync(
    join(root, ".operator-data", "people.json"),
    JSON.stringify({ people: [{ name: "Usman", role: "owner", tailscale: [LOGIN.usman] }, { name: "Mehroz", role: "co-founder", tailscale: [LOGIN.mehroz] }] }),
  );
  const store = new DeviceStore(root);
  const tokenEnv = { MU_LOCAL_OWNER_TOKEN_FILE: join(root, "local-owner.token") };
  const localOwnerProof = role === "server" ? createLocalOwnerProof(root, tokenEnv) : undefined;
  const pairedCookie = store.mintSession("mehroz", "Mehroz's phone", "tailnet").cookie;
  const mehrozCompanion = store.registerCompanion("mehroz", { label: "Mehroz's PC" }).token;
  const usmanCompanion = store.registerCompanion("usman", { label: "Usman's laptop" }).token;
  const sharedComputer = store.registerComputer({ name: "matrix-bot", adapter: "synthetic", createdBy: "usman" }).token;
  const tailnet = syntheticTailnetForTests(MATRIX_TAILNET, ["100.64.0.1"]);
  const gate = createPrincipalGate({
    root,
    internalToken: () => MATRIX_INTERNAL,
    store,
    tailnetName: MATRIX_TAILNET,
    servePeer: () => true,
    tailnet,
    ...(role === undefined ? {} : { role }),
    ...(localOwnerProof ? { localOwnerProof } : {}),
  } as never);
  // A plain loopback socket forging Serve's headers: the socket's peer is NOT tailscaled.
  const forgeGate = createPrincipalGate({
    root,
    internalToken: () => MATRIX_INTERNAL,
    store,
    tailnetName: MATRIX_TAILNET,
    servePeer: () => false,
    tailnet,
    ...(role === undefined ? {} : { role }),
    ...(localOwnerProof ? { localOwnerProof } : {}),
  } as never);
  const serve = (login: string, extra: Record<string, string> = {}) => ({ host: `${MATRIX_TAILNET}:8443`, "tailscale-user-login": login, "x-forwarded-for": "100.64.0.9", "x-forwarded-proto": "https", ...extra });

  function request(kind: CallerKind, method: string, path: string, extra: Record<string, string>, proofMode?: ProofMode) {
    let remote = "127.0.0.1";
    let headers: Record<string, string> = {};
    let useGate = gate;
    switch (kind) {
      case "loopback-owner": {
        headers = { host: "127.0.0.1:8081" };
        // Server role: the owner's legitimate callers carry the proof (an unset role never reads the token).
        const mode: ProofMode = proofMode ?? (role === "server" ? "header" : "none");
        const token = readLocalOwnerToken(root, tokenEnv);
        if (mode === "header" && token) headers["x-mu-local-owner"] = token;
        if (mode === "bearer" && token) headers.authorization = `Bearer ${token}`;
        if (mode === "wrong") headers["x-mu-local-owner"] = "A".repeat(43);
        break;
      }
      case "tailnet-founder":
        headers = serve(LOGIN.mehroz);
        break;
      case "paired-founder":
        headers = serve(LOGIN.mehroz, { cookie: `mu_session=${encodeURIComponent(pairedCookie)}` });
        break;
      case "companion-remote":
        headers = serve(LOGIN.mehroz, { authorization: `Bearer ${mehrozCompanion}` });
        break;
      case "companion-local":
        headers = { host: "127.0.0.1:8081", authorization: `Bearer ${usmanCompanion}` };
        break;
      case "bridge-client":
        headers = { host: "127.0.0.1:8081", authorization: `Bearer ${sharedComputer}`, "x-mu-bridge": "1" };
        break;
      case "anonymous-lan":
        remote = "192.168.1.20";
        headers = { host: "192.168.1.5:8081" };
        break;
      case "forged-lan":
        remote = "192.168.1.20";
        headers = serve(LOGIN.usman);
        break;
      case "forged-loopback":
        headers = serve(LOGIN.usman);
        useGate = forgeGate;
        break;
    }
    const req = { url: path, method, headers: { ...headers, ...extra }, socket: { remoteAddress: remote } } as unknown as IncomingMessage;
    const out: { status: number; reached: boolean; body: any; headers: Record<string, string | undefined> } = { status: 200, reached: false, body: null, headers: {} };
    const res = {
      statusCode: 200,
      setHeader() {},
      getHeader() {
        return undefined;
      },
      end(text?: string) {
        try {
          out.body = text ? JSON.parse(text) : null;
        } catch {
          out.body = text ?? null;
        }
      },
    } as unknown as ServerResponse;
    return { req, res, out, gate: useGate };
  }

  return {
    token: () => readLocalOwnerToken(root, tokenEnv),
    tokenFile: tokenEnv.MU_LOCAL_OWNER_TOKEN_FILE,
    pairedCookie,
    decide(kind, method, path, extra = {}, onReach, opts) {
      const { req, res, out, gate: g } = request(kind, method, path, extra, opts?.proof);
      g(req, res, () => {
        out.reached = true;
        onReach?.(req);
      });
      out.status = out.reached ? 200 : res.statusCode;
      out.headers = Object.fromEntries(Object.entries(req.headers).map(([k, v]) => [k, Array.isArray(v) ? v.join(",") : v]));
      return out;
    },
    close() {
      try {
        rmSync(root, { recursive: true, force: true, maxRetries: 3, retryDelay: 50 });
      } catch {
        /* a SQLite handle may linger briefly on Windows; the OS reclaims the temp dir */
      }
    },
  };
}

/** The route keys and the methods the table covers: every ROUTES entry, a read and a write. */
export const MATRIX_ROUTES = Object.keys(ROUTES).sort();
export const MATRIX_METHODS = ["GET", "POST"] as const;

/** `route METHOD` -> one status per caller kind, in CALLER_KINDS order. Generated from the real gate. */
export function decisionTable(role: MatrixRole): Record<string, number[]> {
  const rig = makeRig(role);
  try {
    const table: Record<string, number[]> = {};
    for (const route of MATRIX_ROUTES)
      for (const method of MATRIX_METHODS) table[`${method} ${route}`] = CALLER_KINDS.map((kind) => rig.decide(kind, method, route).status);
    return table;
  } finally {
    rig.close();
  }
}
