import { afterAll, describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { refuseUnlessAtThisPc, requestAtHub } from "./gate";
import { pageTokenFor } from "./principal";
import { CALLER_KINDS, decisionTable, MATRIX_INTERNAL, makeRig, type CallerKind } from "./role-matrix";
import { ROUTES, routeClass, routeRule } from "./routes";
import { CONSOLE_ONLY, consoleOnlyRule, OWNER_PRIVATE_OPEN_TO_BOTH_FOUNDERS, OWNER_PRIVATE_ROUTES } from "./server-role";

/**
 * MU_HUB_ROLE=server (headless Windows hub). The tables below are GENERATED by running the real identity gate
 * (role-matrix.ts) for every ROUTES entry x GET/POST x each kind of caller: nothing is written per route.
 *
 *  - pc, cloud and an unset role must reproduce fixtures/legacy-route-decisions.json, which was generated from
 *    the gate before the server role existed (commit f9cadcaa). That is the "byte-for-byte as today" proof.
 *  - server differs from pc in exactly one place: a founder holding a confirmed human session, on a local-owner
 *    route that is not console-only. Every other caller, route and method is identical.
 */

const legacy = JSON.parse(readFileSync(join(import.meta.dir, "fixtures", "legacy-route-decisions.json"), "utf8")) as Record<string, string>;
const legacyTable = Object.fromEntries(Object.entries(legacy).filter(([k]) => !k.startsWith("_"))) as Record<string, string>;
const flat = (t: Record<string, number[]>) => Object.fromEntries(Object.entries(t).map(([k, v]) => [k, v.join(",")]));

const tables = { unset: decisionTable(undefined), pc: decisionTable("pc"), cloud: decisionTable("cloud"), server: decisionTable("server") };
const col = (kind: CallerKind) => CALLER_KINDS.indexOf(kind);

describe("pc and cloud are exactly what they were before the server role", () => {
  test("the legacy fixture covers every ROUTES entry, a read and a write, every caller kind", () => {
    expect(Object.keys(legacyTable).length).toBe(Object.keys(ROUTES).length * 2);
    for (const row of Object.values(legacyTable)) expect(row.split(",").length).toBe(CALLER_KINDS.length);
  });
  for (const role of ["unset", "pc", "cloud"] as const)
    test(`${role}: every decision equals the pre-change gate's (except the bare tailnet login, tightened by acceptance #18)`, () => {
      const now = flat(tables[role]);
      // One intended change since the fixture: a bare tailnet login (no confirmed session) reaches no shared /__ route except the
      // data-free status ones (gate.ts TAILNET_LOGIN_MAY). Every other caller column must still match the fixture exactly.
      const bare = col("tailnet-founder");
      const others = (row: string) => row.split(",").filter((_, i) => i !== bare).join(",");
      const differing = Object.keys(legacyTable).filter((k) => others(now[k] ?? "") !== others(legacyTable[k])).map((k) => `${k}: was ${legacyTable[k]}, now ${now[k]}`);
      expect(differing).toEqual([]);
      for (const k of Object.keys(legacyTable)) {
        const [method, path] = k.split(" ");
        const was = Number(legacyTable[k].split(",")[bare]);
        const is = Number(now[k].split(",")[bare]);
        if (!path.startsWith("/__") || /^\/__(version|health)\b/.test(path) || routeClass(path, method) !== "shared" || was >= 400) expect([k, is]).toEqual([k, was]);
        else expect([k, is]).toEqual([k, 403]);
      }
      expect(Object.keys(now).sort()).toEqual(Object.keys(legacyTable).sort());
    });
  test("pc and cloud are identical to each other at the gate (the cloud difference is the 501 in hub-role.ts)", () => {
    expect(flat(tables.cloud)).toEqual(flat(tables.pc));
  });
});

describe("server role: the generated decision table differs from pc only for a confirmed founder on an open local-owner route", () => {
  const changed: Array<{ key: string; kind: CallerKind; was: number; now: number }> = [];
  /** The data-free supervisor liveness: an unproven loopback GET /__version answers {ok:true} (the one cell that is not a founder's). */
  const liveness: string[] = [];
  const isLiveness = (key: string, kind: CallerKind) => key === "GET /__version" && kind === "bridge-client";
  for (const [key, row] of Object.entries(tables.server))
    row.forEach((now, i) => {
      const was = tables.pc[key][i];
      if (was === now) return;
      if (isLiveness(key, CALLER_KINDS[i])) liveness.push(`${key} ${CALLER_KINDS[i]} ${was}->${now}`);
      else changed.push({ key, kind: CALLER_KINDS[i], was, now });
    });

  test("the only other change is the liveness cell: a loopback caller with no principal and no proof gets {ok:true} from GET /__version", () => {
    expect(liveness).toEqual(["GET /__version bridge-client 401->200"]);
  });

  test("every changed cell is paired-founder, 403 -> 200, on a local-owner route that is not console-only", () => {
    expect(changed.length).toBeGreaterThan(40);
    for (const c of changed) {
      const [method, route] = [c.key.split(" ")[0], c.key.split(" ")[1]];
      expect([c.key, c.kind, c.was, c.now]).toEqual([c.key, "paired-founder", 403, 200]);
      expect(routeClass(route, method)).toBe("local-owner");
      expect(consoleOnlyRule(route)).toBeNull();
    }
  });

  test("conversely: every paired-founder cell on a local-owner route is 200, or 403 when console-only", () => {
    for (const [key, row] of Object.entries(tables.server)) {
      const [method, route] = key.split(" ");
      if (routeClass(route, method) !== "local-owner") continue;
      expect([key, row[col("paired-founder")]]).toEqual([key, consoleOnlyRule(route, undefined, method) ? 403 : 200]);
    }
  });

  test("the bare Tailscale login (a process), the loopback owner, companions, bridge clients and every LAN caller are untouched", () => {
    for (const kind of CALLER_KINDS.filter((k) => k !== "paired-founder"))
      for (const key of Object.keys(tables.pc).filter((k) => !isLiveness(k, kind))) expect([key, kind, tables.server[key][col(kind)]]).toEqual([key, kind, tables.pc[key][col(kind)]]);
  });

  test("the loopback owner keeps console-only routes; nobody else gets them", () => {
    for (const route of Object.keys(CONSOLE_ONLY).filter((r) => r in ROUTES))
      for (const method of ["GET", "POST"]) {
        const row = tables.server[`${method} ${route}`];
        expect([route, method, row[col("loopback-owner")]]).toEqual([route, method, 200]);
        if (routeClass(route, method) === "local-owner") expect([route, method, row[col("paired-founder")]]).toEqual([route, method, 403]);
      }
  });

  test("the required console-only routes are all in the set and refuse a confirmed founder", () => {
    for (const route of ["/__design_set_key", "/__design_remove_key", "/__ccr_pin_routes", "/__dev_restart", "/__start_voice", "/__hermes_cmd", "/__hermes_effort", "/__hermes_moa_save"]) {
      expect(consoleOnlyRule(route)).not.toBeNull();
      for (const method of ["GET", "POST"]) expect([route, method, tables.server[`${method} ${route}`][col("paired-founder")]]).toEqual([route, method, 403]);
    }
    // Connect's prefix rule: sub-paths follow, look-alike siblings do not.
    expect(consoleOnlyRule("/__hermes_cmd/run")?.key).toBe("/__hermes_cmd");
    expect(consoleOnlyRule("/__claude_chat")).toBeNull();
    expect(consoleOnlyRule("/__claude")?.key).toBe("/__claude");
  });

  test("every console-only entry names a reason", () => {
    for (const [k, why] of Object.entries(CONSOLE_ONLY)) expect([k, why.length > 10]).toEqual([k, true]);
  });

  test("owner-private data (criterion 4) is open to a confirmed founder in one place, and the one switch closes it", () => {
    expect(OWNER_PRIVATE_OPEN_TO_BOTH_FOUNDERS).toBe(true);
    for (const route of Object.keys(OWNER_PRIVATE_ROUTES)) {
      expect(route in ROUTES).toBe(true);
      expect(routeRule(route).read).toBe("local-owner");
      for (const method of ["GET", "POST"]) expect([route, method, tables.server[`${method} ${route}`][col("paired-founder")]]).toEqual([route, method, 200]);
      expect(consoleOnlyRule(route)).toBeNull();
      expect(consoleOnlyRule(route, false)?.key).toBe(route); // the one-line reversal
    }
  });

  test("a bare Tailscale login gets a plain 'pair this browser' answer, a console-only route a different one", () => {
    const rig = makeRig("server");
    try {
      const bare = rig.decide("tailnet-founder", "POST", "/__claude_chat");
      expect(bare.status).toBe(403);
      expect(bare.body).toMatchObject({ reason: "needs-human-session", route: "/__claude_chat" });
      const closed = rig.decide("paired-founder", "POST", "/__design_set_key");
      expect(closed.status).toBe(403);
      expect(closed.body).toMatchObject({ reason: "console-only", route: "/__design_set_key" });
      // Deny by default survives: an unclassified path is local-owner AND console-only, so a founder never reaches it.
      expect(rig.decide("paired-founder", "GET", "/__brand_new").status).toBe(403);
    } finally {
      rig.close();
    }
  });
});

describe("what a granted founder's request carries downstream", () => {
  const rig = makeRig("server");
  afterAll(() => rig.close());
  const own = pageTokenFor({ personId: "mehroz", via: "paired-session" }, MATRIX_INTERNAL);

  test("the inline hub-only guards (requestAtHub, refuseUnlessAtThisPc) accept the admitted founder, only for that request", () => {
    let atHub: boolean | null = null;
    let refusal: unknown = "unset";
    const r = rig.decide("paired-founder", "POST", "/__lead-sites/generate", {}, (req) => {
      atHub = requestAtHub(req as never, { root: process.cwd() });
      refusal = refuseUnlessAtThisPc(req as never, "nope", { root: process.cwd() });
    });
    expect(r.status).toBe(200);
    expect(atHub).toBe(true);
    expect(refusal).toBeNull();
  });

  test("a founder refused at the gate never reaches a handler, and a shared route gets no grant", () => {
    let reached = false;
    expect(rig.decide("tailnet-founder", "POST", "/__claude_chat", {}, () => (reached = true)).status).toBe(403);
    expect(rig.decide("paired-founder", "POST", "/__design_set_key", {}, () => (reached = true)).status).toBe(403);
    expect(reached).toBe(false);
    let atHub: boolean | null = null;
    expect(rig.decide("paired-founder", "GET", "/__operator/leads", {}, (req) => (atHub = requestAtHub(req as never, { root: process.cwd() }))).status).toBe(200);
    expect(atHub).toBe(false); // /__operator is shared: its own per-request device rules still see a remote founder
  });

  test("the founder's own page token becomes the internal one for the route's legacy write check; any other value is left alone", () => {
    expect(rig.decide("paired-founder", "POST", "/__claude_chat", { "x-claude-os-token": own }).headers["x-claude-os-token"]).toBe(MATRIX_INTERNAL);
    expect(rig.decide("paired-founder", "POST", "/__claude_chat", { "x-claude-os-token": "p1.forged" }).headers["x-claude-os-token"]).toBe("p1.forged");
    // The raw internal token from a remote caller is stripped (existing behaviour), never honoured.
    expect(rig.decide("paired-founder", "POST", "/__claude_chat", { "x-claude-os-token": MATRIX_INTERNAL }).headers["x-claude-os-token"]).toBeUndefined();
    // Usman's page token does not work for Mehroz.
    const usmans = pageTokenFor({ personId: "usman", via: "paired-session" }, MATRIX_INTERNAL);
    expect(rig.decide("paired-founder", "POST", "/__claude_chat", { "x-claude-os-token": usmans }).headers["x-claude-os-token"]).toBe(usmans);
    // On a shared route nothing is swapped (a remote founder keeps his own token; pageTokenOk checks it).
    expect(rig.decide("paired-founder", "POST", "/__operator/leads", { "x-claude-os-token": own }).headers["x-claude-os-token"]).toBe(own);
  });

  test("a forged Serve login on a plain loopback socket is nobody in server role: 401, no grant", () => {
    let reached = false;
    for (const path of ["/__claude_chat", "/__design_set_key", "/__operator/leads", "/"]) expect(rig.decide("forged-loopback", "GET", path, {}, () => (reached = true)).status).toBe(401);
    expect(reached).toBe(false);
  });
});
